/* Make author avatar larger */
.author__avatar img {
  max-width: 180px;   /* default is 120px */
  border-radius: 50%;
}

.author__avatar {
  margin-bottom: 1rem;
}


sass:
  sass_dir: _sass
  style: compressed

# Add this if not already
include:
  - assets
